name: Trigger auto deployment for container-app-zsutfynehbw7u

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-zsutfynehbw7u-AutoDeployTrigger-36e423d7-7b07-4e53-8711-7e8ff11c7115.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPZSUTFYNEHBW7U_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPZSUTFYNEHBW7U_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPZSUTFYNEHBW7U_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryzsutfynehbw7u.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPZSUTFYNEHBW7U_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPZSUTFYNEHBW7U_REGISTRY_PASSWORD }}
          containerAppName: container-app-zsutfynehbw7u
          resourceGroup: expresssample903f8d04
          imageToBuild: containerregistryzsutfynehbw7u.azurecr.io/container-app-zsutfynehbw7u:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


